grails_gym_hsseine/grails-app/domain/emsi/mbds/Annonce.groovy
package emsi.mbds

class Annonce {

    String title
    String description
    Float price
    String ref
    Boolean status = Boolean.FALSE

    Date dateCreated
    Date lastUpdated

    List illustrations

    static hasMany = [illustrations: Illustration]

    static belongsTo = [author: User]

    static constraints = {
        title nullable: false, blank: false, size: 3..55
        description nullable: false, blank: false
        price nullable: true, scale: 2, min: 0F
        ref nullable: false, blank: false, unique: true
        status nullable: false
    }

    static mapping = {
        description type: 'text'
    }
}

grails_gym_hsseine/grails-app/controllers/emsi/mbds/AnnonceController.groovy
package emsi.mbds

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException

import static org.springframework.http.HttpStatus.*

@Secured(['ROLE_ADMIN', 'ROLE_MODO'])
class AnnonceController {

    AnnonceService annonceService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond annonceService.list(params), model: [annonceCount: annonceService.count()]
    }

    def show(Long id) {
        respond annonceService.get(id)
    }

    def create() {
        respond new Annonce(params)
    }

    def save(Annonce annonce) {
        if (annonce == null) {
            notFound()
            return
        }

        try {

            def image = request.getFile('image')
            if (!image.isEmpty()) {
                def illustration = new Illustration()
                def uuid = UUID.randomUUID()
                illustration.setFilename(uuid.toString() + annonce.getTitle() + ".png")
                def illustrations = new ArrayList<Illustration>()
                illustrations.add(illustration)
                image.transferTo(new File(grailsApplication.config.assets.path + uuid.toString() + annonce.getTitle() + ".png"))
                illustration.setAnnonce(annonce)
                annonce.setIllustrations(illustrations)
            }
            annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view: 'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*' { respond annonce, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond annonceService.get(id)
    }

    def update(Annonce annonce) {
        if (annonce == null) {
            notFound()
            return
        }

        try {
            annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view: 'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*' { respond annonce, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        annonceService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'annonce.label', default: 'Annonce'), id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'annonce.label', default: 'Annonce'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails_gym_hsseine/grails-app/views/annonce/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
    <div class="btn-group">
        <button type="button" class="btn btn-info"><a style="color: white; text-decoration: none" href="#create-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a></button>
        <button type="button" class="btn btn-secondary"><a style="color: white; text-decoration: none" class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></button>
        <button type="button" class="btn btn-warning"><g:link style="color: white; text-decoration: none" class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></button>

    </div>
    <br> <br>
    <div id="create-annonce" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.annonce}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.annonce}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.annonce}" method="POST" enctype="multipart/form-data">
                <fieldset class="form">
                    <input type="file" name="image">
                    <f:all bean="annonce"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="btn btn-success btn-block save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails_gym_hsseine/grails-app/views/annonce/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-annonce" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.annonce}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.annonce}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.annonce}" method="PUT">
                <g:hiddenField name="version" value="${this.annonce?.version}" />
                <fieldset class="form">
                    <f:all bean="annonce"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails_gym_hsseine/grails-app/views/annonce/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="btn-group">
    <button type="button" class="btn btn-info"><a style="color: white; text-decoration: none" href="#list-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                                                             default="Skip to content&hellip;"/></a></button>
    <button type="button" class="btn btn-secondary"><a style="color: white; text-decoration: none" class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></button>
    <button type="button" class="btn btn-warning"><g:link style="color: white; text-decoration: none" class="create" action="create"><g:message code="default.new.label"
                                                                                                    args="[entityName]"/></g:link></button>
</div>
<br><br>
<div id="list-annonce" class="content scaffold-list" role="main">
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <p class="card-title">Les annonces</p>

                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <table id="annonces" class="display expandable-table" style="width:100%">
                                    <thead>
                                    <tr>
                                        <th>#Ref</th>
                                        <th>Illustrations</th>
                                        <th>Titre</th>
                                        <th>Description</th>
                                        <th>Date de publication</th>
                                        <th>Publié par</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <g:each in="${annonceList}">
                                        <tr>
                                            <td>${it.ref}</td>
                                            <td>
                                                <g:each in="${it.illustrations}" var="ill">
                                                <g:img file="${ill.filename}" />
                                                </g:each>
                                            </td>
                                            <td><g:link controller="annonce" action="show" id="${it.id}">${it.title}</g:link></td>
                                            <td>${it.description}</td>
                                            <td>${it.dateCreated}</td>
                                            <td><g:link controller="user" action="show" id="${it.author.id}">${it.author.username}</g:link></td>
                                        </tr>
                                    </g:each>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="pagination">
    <g:paginate total="${annonceCount ?: 0}"/>
</div>
</div>
</body>
</html>

grails_gym_hsseine/grails-app/views/annonce/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
    <div class="btn-group">
        <button type="button" class="btn btn-info"><a style="color: white; text-decoration: none" href="#list-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                                                                                                             default="Skip to content&hellip;"/></a></button>
        <button type="button" class="btn btn-secondary"><a style="color: white; text-decoration: none" class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></button>
        <button type="button" class="btn btn-warning"><g:link style="color: white; text-decoration: none" class="create" action="create"><g:message code="default.new.label"
                                                                                                                                                    args="[entityName]"/></g:link></button>
    </div> <br> <br>
        <div id="show-annonce" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <table class="table table-hover">
                <tbody>
                <tr>
                    <td>Title</td>
                    <td>${annonce.title}</td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td>${annonce.description}</td>
                </tr>
                <tr>
                    <td>Price</td>
                    <td>${annonce.price}</td>
                </tr>
                <tr>
                    <td>Ref</td>
                    <td>${annonce.ref}</td>
                </tr>
                <tr>
                    <td>Status</td>
                    <td>${annonce.status}</td>
                </tr>
                <tr>
                    <td>Illustrations</td>
                    <td>
                        <ul>
                        <g:each in="${annonce.illustrations}" var="illustration">
                            <li>
                                <g:img dir="images" file="${illustration.filename}" alt="illustration"/>
                            </li>
                        </g:each>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>Author</td>
                    <td><g:link controller="user" action="show" id="${annonce.author.id}">${annonce.author.username}</g:link></td>
                </tr>
                </tbody>
            </table>
            <br> <br>
            <g:form resource="${this.annonce}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="btn btn-warning" action="edit" resource="${this.annonce}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="btn btn-danger" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>